---

- name: "In ubuntu fix the docker.service file which iverlaps with daemon.json"
  lineinfile:
    path: /lib/systemd/system/docker.service
    regexp: '^ExecStart=/usr/bin/dockerd -H fd://'
    # regexp: '^\+ \: root \: ALL'
    line: 'ExecStart=/usr/bin/dockerd'
  register: ddaemon
  when: ansible_os_family == 'Debian'

- name: "systemctl daemon-reload"
  command: systemctl daemon-reload
  when: (ddaemon|changed)

- name: "Set docker_config_hosts based if docker_default_tcp_listen is true"
  set_fact:
    docker_config_hosts:
      - "unix://{{ docker_config_sock }}"
      - "tcp://{{ docker_config_ip }}:{{ docker_config_port }}"
  when: docker_default_tcp_listen == true

- name: "Set docker_config_hosts based if docker_default_tcp_listen is false"
  set_fact:
    docker_config_hosts:
      - "unix://{{ docker_config_sock }}"
  when: docker_default_tcp_listen == false

- name: create docker config directory
  file:
    path: /etc/docker
    state: directory
    mode: 0600
    owner: root
    group: root

# configure docker deamon json file
- name: configure docker daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0400
    owner: root
    group: "{{ docker_group }}"
  notify: restart docker
