---
- name: "Install system requirements"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ docker_packages }}"

# - apt_key:
#     data: "{{ lookup('file', 'docker-apt-key') }}"
#     state: present
- name: "Add apt-key via curl [quick and dirty ...]"
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: "Add repository"
  apt_repository:
    repo: "{{ docker_repo_url }}"
    state: present
    update_cache: yes

# - name: "Verify that apt is pulling from the right repository"
#   command: apt-cache policy docker-engine
